<a href="https://colab.research.google.com/github/pasumarthi/Backprop/blob/master/LSTM_sandbox.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

We were trying to explore the difference parameters of RNN,GRU and LSTM of keras while trying to solve different kind of NLP problems. As part of this we went n depth for  return_sequence and return state parameters of the LSTM in keras

In [0]:
from keras.models import Model
from keras.layers import Input
from keras.layers import LSTM, RNN, GRU
from numpy import array


Using TensorFlow backend.


Running the example outputs a single hidden state for the input sequence with 3 time steps.

keras.layers.**RNN**(**cell**, **return_sequences**=False, **return_state**=False, go_backwards=False, stateful=False, unroll=False)

keras.layers.**GRU**(**units**, **activation**='tanh', **recurrent_activation**='hard_sigmoid', use_bias=True, **kernel_initializer**='glorot_uniform', recurrent_initializer='orthogonal', bias_initializer='zeros', kernel_regularizer=None, recurrent_regularizer=None, bias_regularizer=None, activity_regularizer=None, kernel_constraint=None, recurrent_constraint=None, bias_constraint=None, dropout=0.0, recurrent_dropout=0.0, implementation=1, **return_sequences**=False, **return_state**=False, go_backwards=False, **stateful**=False, unroll=False, reset_after=False)

keras.layers.**LSTM**(**units**, **activation**='tanh', **recurrent_activation**='hard_sigmoid', use_bias=True, **kernel_initializer**='glorot_uniform', **recurrent_initializer**='orthogonal', bias_initializer='zeros', unit_forget_bias=True, kernel_regularizer=None, recurrent_regularizer=None, bias_regularizer=None, activity_regularizer=None, kernel_constraint=None, recurrent_constraint=None, bias_constraint=None, dropout=0.0, recurrent_dropout=0.0, implementation=1, **return_sequences**=False, **return_state**=False, go_backwards=False, **stateful**=False, unroll=False)


Arguments:
- **units**: Positive integer, dimensionality of the output space.
- **activation**: Activation function to use. Default: hyperbolic tangent (tanh). If you pass None, no activation is applied (ie. "linear" activation: a(x) = x).
- **recurrent_activation**: Activation function to use for the recurrent step. Default: hard sigmoid (hard_sigmoid). If you pass None, no activation is applied (ie. "linear" activation: a(x) = x).
- **use_bias**: Boolean, whether the layer uses a bias vector.
- **kernel_initializer**: Initializer for the kernel weights matrix, used for the linear transformation of the inputs..
- **recurrent_initializer**: Initializer for the recurrent_kernel weights matrix, used for the linear transformation of the recurrent state..
- **bias_initializer**: Initializer for the bias vector.
- **unit_forget_bias**: Boolean. If True, add 1 to the bias of the forget gate at initialization. Setting it to true will also force bias_initializer="zeros". This is recommended in Jozefowicz et al.
- **kernel_regularizer**: Regularizer function applied to the kernel weights matrix.
- **recurrent_regularizer**: Regularizer function applied to the recurrent_kernel weights matrix.
- **bias_regularizer**: Regularizer function applied to the bias vector.
- **activity_regularizer**: Regularizer function applied to the output of the layer (its "activation")..
- **kernel_constraint**: Constraint function applied to the kernel weights matrix.
- **recurrent_constraint**: Constraint function applied to the recurrent_kernel weights matrix.
- **bias_constraint**: Constraint function applied to the bias vector.
- **dropout**: Float between 0 and 1. Fraction of the units to drop for the linear transformation of the inputs.
- **recurrent_dropout**: Float between 0 and 1. Fraction of the units to drop for the linear transformation of the recurrent state.
- **implementation**: Implementation mode, either 1 or 2. Mode 1 will structure its operations as a larger number of smaller dot products and additions, whereas mode 2 will batch them into fewer, larger operations. These modes will have different performance profiles on different hardware and for different applications.
- **return_sequences**: Boolean. Whether to return the last output. in the output sequence, or the full sequence.
- **return_state**: Boolean. Whether to return the last state in addition to the output.
- **go_backwards**: Boolean (default False). If True, process the input sequence backwards and return the reversed sequence.
- **stateful**: Boolean (default False). If True, the last state for each sample at index i in a batch will be used as initial state for the sample of index i in the following batch.
- **unroll**: Boolean (default False). If True, the network will be unrolled, else a symbolic loop will be used. Unrolling can speed-up a RNN, although it tends to be more memory-intensive. Unrolling is only suitable for short sequences.

In [0]:
# define model
units = 2
inputs1 = Input(shape=(2, 3))
lstm1 =LSTM(units)(inputs1)
lstm2 =LSTM(units, return_sequences=True)(inputs1)
lstm3 =LSTM(units, return_state=True)(inputs1)
lstm4 =LSTM(units, return_sequences=True, return_state=True)(inputs1)
model1 = Model(inputs=inputs1, outputs=lstm1)
model2 = Model(inputs=inputs1, outputs=lstm2)
model3 = Model(inputs=inputs1, outputs=lstm3)
model4 = Model(inputs=inputs1, outputs=lstm4)
model4.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         (None, 2, 3)              0         
_________________________________________________________________
lstm_8 (LSTM)                [(None, 2, 2), (None, 2), 48        
Total params: 48
Trainable params: 48
Non-trainable params: 0
_________________________________________________________________


In [0]:
import numpy as np
data = np.array([[[0.1, 0.2, 0.3],[0.1, 0.2, 0.3]],[[0.1, 0.2, 0.3],[0.1, 0.2, 0.3]]])

np.shape(data)

(2, 2, 3)

In [0]:
# define input data
# (1,2,3) ==> 1 is batch size, 2 is time steps, 3 is embedding dimensions 
#data = array([[0.1, 0.2, 0.3],[0.1, 0.2, 0.3]]).reshape((1,2,3))
data = array([[[0.1, 0.2, 0.3],[0.1, 0.2, 0.3]],[[0.1, 0.2, 0.3],[0.1, 0.2, 0.3]]])


In [0]:
# make and show prediction
import numpy as np
print(model1.predict(data))
print("---------------------")
print("one array with three outputs at each time step, dimensions of vector at each time step is equal to number of LSTM units")
print(model2.predict(data))
print("---------------------")
print("three array: one for output at last time step of the LSTM, second for LSTM hidden state, third for LSTM cell state")
print(model3.predict(data))
print("---------------------")
print("three array: one for three time steps of the LSTM, second for LSTM hidden state, third for LSTM cell state")
print(model4.predict(data))

[[-0.10812485 -0.0625482 ]
 [-0.10812485 -0.0625482 ]]
---------------------
one array with three outputs at each time step, dimensions of vector at each time step is equal to number of LSTM units
[[[-0.07164414 -0.01564401]
  [-0.10678396 -0.03392722]]

 [[-0.07164414 -0.01564401]
  [-0.10678396 -0.03392722]]]
---------------------
three array: one for output at last time step of the LSTM, second for LSTM hidden state, third for LSTM cell state
[array([[-0.01675767, -0.08862032],
       [-0.01675767, -0.08862032]], dtype=float32), array([[-0.01675767, -0.08862032],
       [-0.01675767, -0.08862032]], dtype=float32), array([[-0.03257203, -0.15509903],
       [-0.03257203, -0.15509903]], dtype=float32)]
---------------------
three array: one for three time steps of the LSTM, second for LSTM hidden state, third for LSTM cell state
[array([[[-0.04197845, -0.02224817],
        [-0.06234686, -0.04087799]],

       [[-0.04197845, -0.02224817],
        [-0.06234686, -0.04087799]]], dtype=floa

- **return_sequences**: Boolean. Whether to return the last output in the output sequence, or the full sequence.
- **return_state**: Boolean. Whether to return the last state in addition to the output.

- **return_sequences**, if True gives the  outputs(y(t)) for all the time steps of the LSTM. If False, gives out only the last time step ouput(y(Ty))
- **return_state**, if True will gives the last time step hidden state(h(Ty)) and cell state(c[Ty]). If False, does not give out any hidden state or cell state.

The layer returns the hidden state for each input time step, then separately, the hidden state output for the last time step and the cell state for the last input time step.

In [0]:
from keras.models import Model
from keras.layers import Input
from keras.layers import LSTM
from numpy import array
# define model
inputs1 = Input(shape=(3, 1))
lstm1, state_h, state_c = LSTM(3, return_sequences=True, return_state=True)(inputs1)
model = Model(inputs=inputs1, outputs=[lstm1, state_h, state_c])
model.summary()
# define input data
data = array([0.1, 0.2, 0.3]).reshape((1,3,1))
# make and show prediction
print(model.predict(data))

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_3 (InputLayer)         (None, 3, 1)              0         
_________________________________________________________________
lstm_9 (LSTM)                [(None, 3, 3), (None, 3), 60        
Total params: 60
Trainable params: 60
Non-trainable params: 0
_________________________________________________________________
[array([[[ 0.00860806, -0.01716868, -0.00297233],
        [ 0.02101759, -0.04590944, -0.00927064],
        [ 0.03448991, -0.08250197, -0.01914189]]], dtype=float32), array([[ 0.03448991, -0.08250197, -0.01914189]], dtype=float32), array([[ 0.0676542 , -0.16215442, -0.03605146]], dtype=float32)]


![alt text](https://i.stack.imgur.com/EFU1S.png)



- GRU has only one hidden state, where both cell state(h) and hidden state(h) merged at the output. This unit is designed to remember longterm dependencied. It is done with the help of update gate, whose weight matrix and biase are updated to learn parameters that makes update active or inactive depending on whether to remember or forget the cell state at every time step 

In the code below we have, we have there conditions:


1.   Both return_sequence and return_state set to False, in this case only the ouput of the last state will be predicted.
2.   return_sequences is True, return_state is False, in this case all the ouputs of every time step will be predicted. We are not using hidden states here.
3. Both return_sequence and return_state set to True, in this case it predicts outputs of all times steps and uses the hidden states of last time step. This is especially useful in the case of seq2seq models where hidden states of encoder are used as initial states(h0,c0) of decoder.



GRU returns one hidden state when return_state is set to True. LSTM returns two states, one hidden state and secod cell state.

In [0]:
# define model
units =2
inputs1 = Input(shape=(3, 1))
lstm1 = GRU(units)(inputs1)
lstm2 = GRU(units, return_sequences=True)(inputs1)
lstm3 = GRU(units, return_state=True)(inputs1)
lstm4 = GRU(units, return_sequences=True, return_state=True)(inputs1)
model1 = Model(inputs=inputs1, outputs=lstm1)
model2 = Model(inputs=inputs1, outputs=lstm2)
model3 = Model(inputs=inputs1, outputs=lstm3)
model4 = Model(inputs=inputs1, outputs=lstm4)
model1.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_4 (InputLayer)         (None, 3, 1)              0         
_________________________________________________________________
gru_1 (GRU)                  (None, 2)                 24        
Total params: 24
Trainable params: 24
Non-trainable params: 0
_________________________________________________________________


In [0]:
# define input data
data = array([0.1, 0.2, 0.3]).reshape((1,3,1))


In [0]:
# make and show prediction
import numpy as np
print(model1.predict(data))
print("---------------------")
print("one array with three outputs at each time step, dimensions of vector at each time step is equal to number of GRU units")
print(model2.predict(data))
print("---------------------")
print("three array: one for output at last time step of the GRU, second for GRU hidden state")
print(model3.predict(data))
print("---------------------")
print("three array: one for three time steps of the GRU, second for GRU hidden state")
print(model4.predict(data))

[[-0.08354472  0.05676868]]
---------------------
one array with three outputs at each time step, dimensions of vector at each time step is equal to number of GRU units
[[[0.04046844 0.04123129]
  [0.10405504 0.09681208]
  [0.17859468 0.15561596]]]
---------------------
three array: one for output at last time step of the GRU, second for GRU hidden state
[array([[ 0.02740779, -0.0357492 ]], dtype=float32), array([[ 0.02740779, -0.0357492 ]], dtype=float32)]
---------------------
three array: one for three time steps of the GRU, second for GRU hidden state
[array([[[-0.00953052,  0.01972705],
        [-0.02074487,  0.04894556],
        [-0.03113053,  0.08277699]]], dtype=float32), array([[-0.03113053,  0.08277699]], dtype=float32)]
